CREATE DATABASE IF NOT EXISTS Face_reco_fill;
USE Face_reco_fill;

-- Create table for attendance records
CREATE TABLE IF NOT EXISTS Attendance (
    ID INT NOT NULL AUTO_INCREMENT,
    ENROLLMENT VARCHAR(100) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DATE VARCHAR(20) NOT NULL,
    TIME VARCHAR(20) NOT NULL,
    SUBJECT VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);